### ISSUE TITLE
Абуз автолата

### ISSUE THREAD

**Issue by Fox231** [animusdev/Fallout-13#13]
1) Сделай себе коробку патронов, которая стоит 4000 металла
2) Наполни обойму патронами
3) Вставь коробку обратно в автолат
4) ???
5) PROFIT.
Вставляя обратно пустую коробку ты возвращаешь 4000 металла и можешь делать сколько угодно патронов.

**Comment by Shluher** [comment]
не абуз а фича

**Comment by kimesik** [comment]
Не абуз, а фича

**Comment by ak72ti** [comment]
пофикшено
