### ISSUE TITLE
Кепки Анклава

### ISSUE THREAD

**Issue by Fox231** [animusdev/Fallout-13#14]
Все кепки теряют спрайт после того, как их одели на голову.
А ещё они убирают спрайт волос. Это очень не красиво выглядит. Поправьте, пожалуйста волосы у кепок и шлемов.

**Comment by ak72ti** [comment]
Кепки анклава пофиксил от части, но я не думаю что это там все кепки, да и не уверен что точно пофиксил. овкорс оставляю открытым. кидайте сюда сломанные кепки. будем думать
