### ISSUE TITLE
Шлем анклава и кнопка воута ложит сервер

### ISSUE THREAD

**Issue by ghost** [animusdev/Fallout-13#17]
Если меньше чем за секунду много раз переключить режим шлема от силовой брони анклава через панель в углу, то сервер фризится. Примерно таким же способом когда начали воут за рестарт можно фризить сервер.

**Comment by ghost** [comment]
Я забыл написать что нужно использовать autoclicker 1.2 на скорости 1мс.

**Comment by ak72ti** [comment]
вкинул sleep, что бы нельзя было быстро это делать.

**Comment by ghost** [comment]
Я тут уже pull request открыл и только сейчас заметил что ты фикс сделал через sleep, у меня фикс через
if(cooldown < world.time - 30)
recent_uses++
