### ISSUE TITLE
Ошибка выбора работы Scriber

### ISSUE THREAD

**Issue by gurland** [animusdev/Fallout-13#3]
После начала раунда при выборе Scriber в окне `Join Game! -> Choose Profession` выдает ошибку `/datum/job/knight is not aviable. Please try another.`

![image](https://user-images.githubusercontent.com/30530987/28781809-025341fa-7614-11e7-8f5e-d040eab277b6.png)

**Comment by ak72ti** [comment]
Пофикшено
