### ISSUE TITLE
Уменьшить количество еды, оружия и прочего

### ISSUE THREAD

**Issue by Enclave2020** [animusdev/Fallout-13#38]
Каждый человек бегает с оружием, патронов **очень** много. Хорошо для КСки, но сервер нацелен на другое
С едой тоже самое, торговать ради еды? Нее, в соседнем здании лежит довоенная еда, что никапли не облучена! (добавьте урон рад урон от всей еды, кроме некоторых, особых видов)
С таким количеством лута просто теряют смысл крышки и еда. Никому ничего не нужно, у всех все есть!

**Comment by ak72ti** [comment]
На форум такие темки, это не проблема а скорее политика
