### ISSUE TITLE
Респавн рейдеров

### ISSUE THREAD

**Issue by Enclave2020** [animusdev/Fallout-13#46]
Что-то в последнее время онлайн сервера значительно упал
Может дело в респавне? Рейдерам лень ждать 3 минуты (а с критом и больше)
Если дело действительно в этом, то пусть они лучше набегают, чем остаться без респавна
Это отчасти создавало сложность и так далее
Не могли же все внезапно наиграться
Давайте если завтра онлайна не будет, то ради теста сделаем респавн мгновенным?

**Comment by ak72ti** [comment]
Для подобных тем есть форум.
