### ISSUE TITLE
Убрать информацию о принадлежности к групировке через Examine

### ISSUE THREAD

**Issue by gurland** [animusdev/Fallout-13#5]
Убрать строчку о принадлежности к группировке через Shift+LMB. Полностью МГшная возможность.

![image](https://user-images.githubusercontent.com/30530987/28785418-11632fe2-761f-11e7-852f-7697f66facdb.png)

**Comment by Fox231** [comment]
Эту инфу должны видеть только члены фракции. Рейдер видит рейдера, анклавовец анклавовца.

**Comment by ak72ti** [comment]
Скорее лучше сделать распознавание с определенного расстояния, скажем 2-3, или 4 тайлов.
