### ISSUE TITLE
NCR trooper problems

### ISSUE THREAD

**Issue by Fox231** [animusdev/Fallout-13#55]
#### Описание проблемы
Когда появляешься за НКР трупера, то в армейском поясе старые магазины 5.56, которые не подходят к автомату, с которым ты появляешься.
#### Разница между ожидаемым поведением и действительным
Пояс должен быть с обоймами rifle magazine (.223), а не с toploader magazine (5.56mm). 
#### Как повторить данную проблему?
Появится за НКР трупера с автоматом Assault Rifle 5.56mm.
#### Дополнительная информация для поиска проблемы
NCR trooper; army belt; toploader magazine (5.56mm); rifle magazine (.223); Assault Rifle 5.56mm;
#### Бинго проблем
- [ ] Проблему получилось повторно воспроизвести хотя бы один раз.
- [x] Проблему получилось повторно воспроизвести несколькими игроками.
- [ ] Проблему получилось повторно воспроизвести в нескольких раундах.
- [x] Проблема была найдена в недавнем раунде(меньше 7 дней).
- [x] [Похожих проблем не было найдено в списке проблем в репозитории](https://github.com/animusdev/Fallout-13/issues)

**Comment by ak72ti** [comment]
починили
