### ISSUE TITLE
Добавить ограничения на рейдера

### ISSUE THREAD

**Issue by gurland** [animusdev/Fallout-13#6]
Убрать возможность ношения рейдером различных высокотехнологичных, а значит сложных в обращении штук (энергетическое оружие, силовая броня).

**Comment by MC-003B** [comment]
Значит, рейдеры - отсталые дебилы? Ты ещё глупее не мог придумать?

**Comment by SilenceInsider** [comment]
Просто добавьте штрафы на использование, ради бога.

**Comment by MC-003B** [comment]
>Штрафы
Дебики сосут из-за рейдеров, а потом плачут. Если ограничивать, то ограничивать и жителей, ибо нехуй выёбываться.

**Comment by SilenceInsider** [comment]
Жители в крайности не впадают.

**Comment by MC-003B** [comment]
Это все равно, что бандитам на сталкере порезать возможность брать стволы в руки.
Чики-брики ножиками, а не обрезами.

**Comment by SilenceInsider** [comment]
Тут проблема в целом в гейм дизайне.

**Comment by MC-003B** [comment]
Тут проблема в неробастных нытиках, которые при грабеже достают дробовики и сосут.
Кучка рейдеров вырезает охуевший Анклав - последние жалуются.

**Comment by Fox231** [comment]
На рейдеров поставлена огромная задача по созданию гнетущей атмосферы опасности. Если не будет рейдеров, то из опасности у вас останется только Анклав, да мобы. Но у Анклава есть лимит на слоты. Вайпается Анклав - остаются только добренькие дурачки-приключенцы, которые лазят по пустым, на скорую руку слепленным городкам в пустошах, которые облутывают в первые же 15 минут раунда. Урезаешь рейдеров - урезаешь веселье.

**Comment by ak72ti** [comment]
Рейдеры не будут ограничены сами по себе, вопрос к силовой броне и сложности добычи энергии в условиях пустоши, но никак не к рейдерам.
