### ISSUE TITLE
Т60 не даёт резистов и дайте старейшине пояс априори

### ISSUE THREAD

**Issue by Nolalot** [animusdev/Fallout-13#60]
#### Описание проблемы
- Да собственно что тут описывать? Старейшина, в т60, пошёл в 113, чуть не уебали скорпионы, подумал ну ок, апнули их. Но когда радтаракан чуть руку мне не отхерачил я понял, что броня нихуя не работает! Ну а пояс, это логично. Или добавить пояса в снаряжение к броне, как в ящиках в 113 том же

#### Разница между ожидаемым поведением и действительным
Без комментариев, т60 не должен пробивать чёртов таракан

#### Как повторить данную проблему?
Зайти в игру на данном билде

#### Дополнительная информация для поиска проблемы

-

#### Продолжительность, в течении которого баг существует
13.08.17

#### Версия клиента BYOND и приблизительное время начала раунда с проблемой
14:00 гдет, дата выше с которой началось

**Comment by Gargule** [comment]
В коде всё норм. Закройте иссуй, если в игре тоже

**Comment by ak72ti** [comment]
сделано
