### ISSUE TITLE
Самовыкоп не работает

### ISSUE THREAD

**Issue by Fox231** [animusdev/Fallout-13#63]
#### Описание проблемы
Пытаюсь выкопать себя, нажимаю Resist. Шкала выполнения доходит до конца и ничего не происходит. Сделал так много раз. Не работает.
#### Бинго проблем
- [ ] Проблему получилось повторно воспроизвести хотя бы один раз.
- [ ] Проблему получилось повторно воспроизвести несколькими игроками.
- [ ] Проблему получилось повторно воспроизвести в нескольких раундах.
- [x] Проблема была найдена в недавнем раунде(меньше 7 дней).
- [x] [Похожих проблем не было найдено в списке проблем в репозитории](https://github.com/animusdev/Fallout-13/issues)

**Comment by ghost** [comment]
Не баг. Он работает, но требует прожать Resist несколько раз. Надо прикрутить уведомление об этом.
