### ISSUE TITLE
Баги новых вендоматов

### ISSUE THREAD

**Issue by Fox231** [animusdev/Fallout-13#68]
#### Описание проблемы
В новых вендоматах не работают кнопки "Set Price" и "Remove".
#### Разница между ожидаемым поведением и действительным
~
#### Как повторить данную проблему?
Открыть вендомат с помощью ключа, положить туда несколько вещей и попробовать изменить им цену или достать из автомата.
#### Дополнительная информация для поиска проблемы
That's Ammo Vending Machine. 
#### Продолжительность, в течении которого баг существует
~
#### Версия клиента BYOND и приблизительное время начала раунда с проблемой
~
#### Бинго проблем
- [x] Проблему получилось повторно воспроизвести хотя бы один раз.
- [ ] Проблему получилось повторно воспроизвести несколькими игроками.
- [ ] Проблему получилось повторно воспроизвести в нескольких раундах.
- [x] Проблема была найдена в недавнем раунде(меньше 7 дней).
- [x] [Похожих проблем не было найдено в списке проблем в репозитории](https://github.com/animusdev/Fallout-13/issues)

**Comment by Liget** [comment]
Я починю сегодня

**Comment by Reishi42** [comment]
Армор тоже, медицинский работает нормально.

**Comment by ak72ti** [comment]
Fixed
