### ISSUE TITLE
Пушки и их проблемы

### ISSUE THREAD

**Issue by Fox231** [animusdev/Fallout-13#7]
Первое - Девяти зарядный дробовик можно повесить только на спину, из-за чего его очень не выгодно носить с собой.
Второе - That's Assault Rifle 5.56mm. Патроны для этой пушки нельзя сделать на автолате, из-за чего эта пушка становится бесполезна после первой же выпущенной обоймы.

**Comment by ak72ti** [comment]
Пожалуй эти два оружия как раз наоборот, отлично сбалансированы, чего нельзя сказать про 10мм автоматы, к которым патронам хоть попой жуй, а обойма 43 патрона. Закрываю за необьективностью.
