### ISSUE TITLE
Тесло-броня Анклава

### ISSUE THREAD

**Issue by Fox231** [animusdev/Fallout-13#8]
У тесло-брони Анклава нету ночного виденья, как у обычной брони. То есть донат броня хуже обычной. FIX

**Comment by Reishi42** [comment]
Вроде есть, я как то раз тестил

**Comment by Fox231** [comment]
ПНВ в шлеме есть, но чтобы его включить оказывается его надо взять в руку и кликнуть по нему.

**Comment by ak72ti** [comment]
Проверено в коде, все работает как и с аналогичной броней других подклассов.
